export const SEED_ITEMS = [
  {
    "id": "seed-1001",
    "sku": "1001",
    "image": "",
    "imageUrl": "",
    "name": "Adze Jacket",
    "category": "Rain/Shells/Jackets",
    "color": "Black",
    "styleNumber": "83526",
    "season": "Fall",
    "year": "2020",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "2.51",
    "discount": "",
    "pricePaid": "13.76",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "Had branding. Removed it from sleeve.",
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "seed-1002",
    "sku": "1002",
    "image": "",
    "imageUrl": "",
    "name": "Back Step Shirt",
    "category": "Short-Sleeve Shirts",
    "color": "Orange",
    "styleNumber": "53139",
    "season": "Spring",
    "year": "2023",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "5.99",
    "discount": "",
    "pricePaid": "9.83",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:01:00.000Z"
  },
  {
    "id": "seed-1003",
    "sku": "1003",
    "image": "",
    "imageUrl": "",
    "name": "Baggies Longs 7\"",
    "category": "Shorts",
    "color": "Tidepool Blue",
    "styleNumber": "58035",
    "season": "Spring",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "65.0",
    "shippingPrice": "6.35",
    "discount": "",
    "pricePaid": "10.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:02:00.000Z"
  },
  {
    "id": "seed-1004",
    "sku": "1004",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater 1/4 Zip",
    "category": "Fleece & Knits",
    "color": "BLST",
    "styleNumber": "25522",
    "season": "Fall",
    "year": "2018",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "7.99",
    "discount": "",
    "pricePaid": "26.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Some pilling. Removed.",
    "createdAt": "2025-01-01T00:03:00.000Z"
  },
  {
    "id": "seed-1005",
    "sku": "1005",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Jacket",
    "category": "Fleece & Knits",
    "color": "Red",
    "styleNumber": "25527",
    "season": "Fall",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "3.75",
    "discount": "",
    "pricePaid": "46.0",
    "condition": "Good",
    "source": "Patagonia Worn Wear",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:04:00.000Z"
  },
  {
    "id": "seed-1006",
    "sku": "1006",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Jacket",
    "category": "Fleece & Knits",
    "color": "Grey",
    "styleNumber": "25527",
    "season": "Fall",
    "year": "2017",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "7.99",
    "discount": "",
    "pricePaid": "16.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Embroidered - removed logo",
    "createdAt": "2025-01-01T00:05:00.000Z"
  },
  {
    "id": "seed-1007",
    "sku": "1007",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Jacket",
    "category": "Fleece & Knits",
    "color": "Black",
    "styleNumber": "25527",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "8.0",
    "discount": "",
    "pricePaid": "20.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:06:00.000Z"
  },
  {
    "id": "seed-1008",
    "sku": "1008",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Vest",
    "category": "Fleece & Knits",
    "color": "Gray",
    "styleNumber": "25881",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "120.0",
    "shippingPrice": "6.0",
    "discount": "",
    "pricePaid": "16.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Embroidered branding on back bottom hem that I removed",
    "createdAt": "2025-01-01T00:07:00.000Z"
  },
  {
    "id": "seed-1009",
    "sku": "1009",
    "image": "",
    "imageUrl": "",
    "name": "Black Hole Duffel Bag 70L",
    "category": "Accessories",
    "color": "",
    "styleNumber": "49347",
    "season": "Fall",
    "year": "2023",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "199.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "89.0",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:08:00.000Z"
  },
  {
    "id": "seed-1010",
    "sku": "1010",
    "image": "",
    "imageUrl": "",
    "name": "Brodeo Beanie",
    "category": "Accessories",
    "color": "Blue",
    "styleNumber": "29206",
    "season": "Fall",
    "year": "2023",
    "size": "Other",
    "sizeOther": "One",
    "listPrice": "49.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "19.6",
    "condition": "New with tags",
    "source": "Backcountry",
    "notes": "",
    "createdAt": "2025-01-01T00:09:00.000Z"
  },
  {
    "id": "seed-1011",
    "sku": "1011",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Thermal Weight Zip-Neck",
    "category": "Thermal Baselayers",
    "color": "Green",
    "styleNumber": "11861",
    "season": "Fall",
    "year": "2012",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "3.15",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "Some glue damage, but overall okay.",
    "createdAt": "2025-01-01T00:10:00.000Z"
  },
  {
    "id": "seed-1012",
    "sku": "1012",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Long-Sleeve Tees",
    "color": "White",
    "styleNumber": "No Tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "4.84",
    "discount": "",
    "pricePaid": "11.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:11:00.000Z"
  },
  {
    "id": "seed-1013",
    "sku": "1013",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "45235",
    "season": "Spring",
    "year": "2020",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "4.55",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:12:00.000Z"
  },
  {
    "id": "seed-1014",
    "sku": "1014",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "45235",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "4.31",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:13:00.000Z"
  },
  {
    "id": "seed-1015",
    "sku": "1015",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Short-Sleeve Tees",
    "color": "Yellow",
    "styleNumber": "No tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "4.3",
    "discount": "",
    "pricePaid": "4.1",
    "condition": "Good",
    "source": "eBay",
    "notes": "No tags",
    "createdAt": "2025-01-01T00:14:00.000Z"
  },
  {
    "id": "seed-1016",
    "sku": "1016",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Trail",
    "category": "Long-Sleeve Tees",
    "color": "Grey",
    "styleNumber": "24485",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "5.26",
    "discount": "",
    "pricePaid": "11.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Good condition - bit worn but no issues.",
    "createdAt": "2025-01-01T00:15:00.000Z"
  },
  {
    "id": "seed-1017",
    "sku": "1017",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Trail",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "24496",
    "season": "Spring",
    "year": "2020",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "6.2",
    "discount": "",
    "pricePaid": "8.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Good condition. Had stains that easily came out.",
    "createdAt": "2025-01-01T00:16:00.000Z"
  },
  {
    "id": "seed-1018",
    "sku": "1018",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Midweight Crew",
    "category": "Thermal Baselayers",
    "color": "Smolder Blue",
    "styleNumber": "No Tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "6.2",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition but missing tags and thumb loops",
    "createdAt": "2025-01-01T00:17:00.000Z"
  },
  {
    "id": "seed-1019",
    "sku": "1019",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Midweight Bottoms",
    "category": "Thermal Baselayers",
    "color": "Grey",
    "styleNumber": "No Tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "4.73",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Most tags cut off, remaining style tag wearing",
    "createdAt": "2025-01-01T00:18:00.000Z"
  },
  {
    "id": "seed-1020",
    "sku": "1020",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Midweight Zip-Neck",
    "category": "Thermal Baselayers",
    "color": "FGE Grey",
    "styleNumber": "44447",
    "season": "Spring",
    "year": "2021",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "6.95",
    "discount": "",
    "pricePaid": "17.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Some pilling",
    "createdAt": "2025-01-01T00:19:00.000Z"
  },
  {
    "id": "seed-1021",
    "sku": "1021",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Thermal Weight Zip-Neck",
    "category": "Thermal Baselayers",
    "color": "SEQR",
    "styleNumber": "43657",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "109.0",
    "shippingPrice": "3.75",
    "discount": "",
    "pricePaid": "38.0",
    "condition": "Good",
    "source": "Patagonia Worn Wear",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:20:00.000Z"
  },
  {
    "id": "seed-1022",
    "sku": "1022",
    "image": "",
    "imageUrl": "",
    "name": "Organic Cotton Corduroy Jeans",
    "category": "Pants",
    "color": "Blue",
    "styleNumber": "58221",
    "season": "Fall",
    "year": "2012",
    "size": "Other",
    "sizeOther": "36",
    "listPrice": "89.0",
    "shippingPrice": "3.84",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "Bit tired, but no issues.",
    "createdAt": "2025-01-01T00:21:00.000Z"
  },
  {
    "id": "seed-1023",
    "sku": "1023",
    "image": "",
    "imageUrl": "",
    "name": "Daily Sweatpants",
    "category": "Pants",
    "color": "Green",
    "styleNumber": "21475",
    "season": "Fall",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "119.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "32.95",
    "condition": "New with tags",
    "source": "eBay",
    "notes": "NWT",
    "createdAt": "2025-01-01T00:22:00.000Z"
  },
  {
    "id": "seed-1024",
    "sku": "1024",
    "image": "",
    "imageUrl": "",
    "name": "Daily Sweatpants",
    "category": "Pants",
    "color": "Gray",
    "styleNumber": "21475",
    "season": "Fall",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "119.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "32.95",
    "condition": "New with tags",
    "source": "eBay",
    "notes": "NWT",
    "createdAt": "2025-01-01T00:23:00.000Z"
  },
  {
    "id": "seed-1025",
    "sku": "1025",
    "image": "",
    "imageUrl": "",
    "name": "Dirt Craft Bike Shorts",
    "category": "Shorts",
    "color": "Beige",
    "styleNumber": "24575",
    "season": "Fall",
    "year": "2017",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "100.0",
    "shippingPrice": "4.62",
    "discount": "",
    "pricePaid": "18.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:24:00.000Z"
  },
  {
    "id": "seed-1026",
    "sku": "1026",
    "image": "",
    "imageUrl": "",
    "name": "Down Sweater Hoody",
    "category": "Insulation",
    "color": "BLYB",
    "styleNumber": "84702",
    "season": "Fall",
    "year": "2023",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "329.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "131.6",
    "condition": "New with tags",
    "source": "Backcountry",
    "notes": "Sold",
    "createdAt": "2025-01-01T00:25:00.000Z"
  },
  {
    "id": "seed-1027",
    "sku": "1027",
    "image": "",
    "imageUrl": "",
    "name": "Down Sweater Vest",
    "category": "Insulation",
    "color": "Green",
    "styleNumber": "84622",
    "season": "Fall",
    "year": "2015",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "229.0",
    "shippingPrice": "12.55",
    "discount": "",
    "pricePaid": "50.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Staining around neck. Thorough washing got it out.",
    "createdAt": "2025-01-01T00:26:00.000Z"
  },
  {
    "id": "seed-1028",
    "sku": "1028",
    "image": "",
    "imageUrl": "",
    "name": "Fezzman Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "",
    "styleNumber": "53962",
    "season": "Spring",
    "year": "2012",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "59.0",
    "shippingPrice": "5.95",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:27:00.000Z"
  },
  {
    "id": "seed-1029",
    "sku": "1029",
    "image": "",
    "imageUrl": "",
    "name": "Go-To Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "SKCY",
    "styleNumber": "52691",
    "season": "Spring",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "40.0",
    "condition": "New with tags",
    "source": "Gift",
    "notes": "",
    "createdAt": "2025-01-01T00:28:00.000Z"
  },
  {
    "id": "seed-1030",
    "sku": "1030",
    "image": "",
    "imageUrl": "",
    "name": "Go-To Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "Blue Agave",
    "styleNumber": "52691",
    "season": "Spring",
    "year": "2015",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "15.0",
    "condition": "Good",
    "source": "Facebook - in person",
    "notes": "Good condition - bit worn but no issues.",
    "createdAt": "2025-01-01T00:29:00.000Z"
  },
  {
    "id": "seed-1031",
    "sku": "1031",
    "image": "",
    "imageUrl": "",
    "name": "Granite Crest Jacket",
    "category": "Rain/Shells/Jackets",
    "color": "FGE",
    "styleNumber": "85415",
    "season": "Spring",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "279.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "117.18",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:30:00.000Z"
  },
  {
    "id": "seed-1032",
    "sku": "1032",
    "image": "",
    "imageUrl": "",
    "name": "Houdini Jacket",
    "category": "Rain/Shells/Jackets",
    "color": "PHGN - Phosphorous Green",
    "styleNumber": "24142",
    "season": "Spring",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "109.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "60.0",
    "condition": "New with tags",
    "source": "Patagonia Store",
    "notes": "",
    "createdAt": "2025-01-01T00:31:00.000Z"
  },
  {
    "id": "seed-1033",
    "sku": "1033",
    "image": "",
    "imageUrl": "",
    "name": "Houdini Jacket",
    "category": "Rain/Shells/Jackets",
    "color": "BALB",
    "styleNumber": "24142",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "109.0",
    "shippingPrice": "5.95",
    "discount": "",
    "pricePaid": "25.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Had large oil stain. Cleaned it out.",
    "createdAt": "2025-01-01T00:32:00.000Z"
  },
  {
    "id": "seed-1034",
    "sku": "1034",
    "image": "",
    "imageUrl": "",
    "name": "Hyper Puff Parka",
    "category": "Insulation",
    "color": "Blue",
    "styleNumber": "84390",
    "season": "Fall",
    "year": "2017",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "300.0",
    "shippingPrice": "15.7",
    "discount": "",
    "pricePaid": "100.0",
    "condition": "New with tags",
    "source": "eBay",
    "notes": "Manufacturer defect, repaired",
    "createdAt": "2025-01-01T00:33:00.000Z"
  },
  {
    "id": "seed-1035",
    "sku": "1035",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Long-Sleeve Tees",
    "color": "Light Green",
    "styleNumber": "52147",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "4.62",
    "discount": "",
    "pricePaid": "9.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Minor oil stains that cleaned out.",
    "createdAt": "2025-01-01T00:34:00.000Z"
  },
  {
    "id": "seed-1036",
    "sku": "1036",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Long-Sleeve Tees",
    "color": "TLRX",
    "styleNumber": "45160",
    "season": "Fall",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "65.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "31.99",
    "condition": "New with tags",
    "source": "Patagonia",
    "notes": "",
    "createdAt": "2025-01-01T00:35:00.000Z"
  },
  {
    "id": "seed-1037",
    "sku": "1037",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Lightweight",
    "category": "Long-Sleeve Tees",
    "color": "",
    "styleNumber": "45641",
    "season": "Spring",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "59.0",
    "shippingPrice": "6.0",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:36:00.000Z"
  },
  {
    "id": "seed-1038",
    "sku": "1038",
    "image": "",
    "imageUrl": "",
    "name": "Long-Sleeved Lightweight Fjord Flannel Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "GTHE",
    "styleNumber": "42410",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "6.79",
    "discount": "",
    "pricePaid": "10.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:37:00.000Z"
  },
  {
    "id": "seed-1039",
    "sku": "1039",
    "image": "",
    "imageUrl": "",
    "name": "Long-Sleeved Lightweight Fjord Flannel Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "Plaid",
    "styleNumber": "42410",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "7.96",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:38:00.000Z"
  },
  {
    "id": "seed-1040",
    "sku": "1040",
    "image": "",
    "imageUrl": "",
    "name": "A/C Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "Orange",
    "styleNumber": "52921",
    "season": "Spring",
    "year": "2008",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "2.31",
    "discount": "",
    "pricePaid": "16.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:39:00.000Z"
  },
  {
    "id": "seed-1041",
    "sku": "1041",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Midweight Crew",
    "category": "Thermal Baselayers",
    "color": "SMDB",
    "styleNumber": "44427",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "37.38",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:40:00.000Z"
  },
  {
    "id": "seed-1042",
    "sku": "1042",
    "image": "",
    "imageUrl": "",
    "name": "Nano Puff Jacket",
    "category": "Insulation",
    "color": "Black",
    "styleNumber": "84212",
    "season": "Fall",
    "year": "2020",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "239.0",
    "shippingPrice": "9.5",
    "discount": "",
    "pricePaid": "39.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Few small holes. Patched.",
    "createdAt": "2025-01-01T00:41:00.000Z"
  },
  {
    "id": "seed-1043",
    "sku": "1043",
    "image": "",
    "imageUrl": "",
    "name": "Nano Puff Vest",
    "category": "Insulation",
    "color": "BLYB",
    "styleNumber": "84242",
    "season": "Fall",
    "year": "2023",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "189.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "56.39",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:42:00.000Z"
  },
  {
    "id": "seed-1044",
    "sku": "1044",
    "image": "",
    "imageUrl": "",
    "name": "Nano-Air Light Hybrid Hoody",
    "category": "Insulation",
    "color": "",
    "styleNumber": "84416",
    "season": "Fall",
    "year": "2023",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "299.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "115.0",
    "condition": "New with tags",
    "source": "REI",
    "notes": "",
    "createdAt": "2025-01-01T00:43:00.000Z"
  },
  {
    "id": "seed-1045",
    "sku": "1045",
    "image": "",
    "imageUrl": "",
    "name": "Organic Cotton T-Shirt",
    "category": "Short-Sleeve Tees",
    "color": "QZCO Orange",
    "styleNumber": "39146",
    "season": "Spring",
    "year": "2018",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "49.0",
    "shippingPrice": "4.25",
    "discount": "",
    "pricePaid": "8.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Good condition - bit worn but no issues.",
    "createdAt": "2025-01-01T00:44:00.000Z"
  },
  {
    "id": "seed-1046",
    "sku": "1046",
    "image": "",
    "imageUrl": "",
    "name": "Organic Cotton Quilt Snap-T Pullover",
    "category": "Fleece & Knits",
    "color": "Green",
    "styleNumber": "25371",
    "season": "Fall",
    "year": "2018",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "149.0",
    "shippingPrice": "9.05",
    "discount": "",
    "pricePaid": "16.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Few tiny holes and wearing around sleeves.",
    "createdAt": "2025-01-01T00:45:00.000Z"
  },
  {
    "id": "seed-1047",
    "sku": "1047",
    "image": "",
    "imageUrl": "",
    "name": "Baggies Lights 6.5\"",
    "category": "Shorts",
    "color": "HEXG",
    "styleNumber": "58046",
    "season": "Spring",
    "year": "2018",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "49.0",
    "shippingPrice": "4.43",
    "discount": "",
    "pricePaid": "10.49",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:46:00.000Z"
  },
  {
    "id": "seed-1048",
    "sku": "1048",
    "image": "",
    "imageUrl": "",
    "name": "Quandary Shorts 12\"",
    "category": "Shorts",
    "color": "Tan",
    "styleNumber": "57839",
    "season": "Spring",
    "year": "2017",
    "size": "Other",
    "sizeOther": "34",
    "listPrice": "89.0",
    "shippingPrice": "3.84",
    "discount": "",
    "pricePaid": "11.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:47:00.000Z"
  },
  {
    "id": "seed-1049",
    "sku": "1049",
    "image": "",
    "imageUrl": "",
    "name": "R1 Air 1/4 Zip",
    "category": "Fleece & Knits",
    "color": "MANR - Mangrove Red",
    "styleNumber": "40245",
    "season": "Spring",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "129.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "89.0",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:48:00.000Z"
  },
  {
    "id": "seed-1050",
    "sku": "1050",
    "image": "",
    "imageUrl": "",
    "name": "R1 Pullover",
    "category": "Fleece & Knits",
    "color": "Viking Blue?",
    "styleNumber": "40110",
    "season": "Fall",
    "year": "2021",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "139.0",
    "shippingPrice": "8.0",
    "discount": "",
    "pricePaid": "28.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:49:00.000Z"
  },
  {
    "id": "seed-1051",
    "sku": "1051",
    "image": "",
    "imageUrl": "",
    "name": "R1 Pullover",
    "category": "Fleece & Knits",
    "color": "GCB - Grecian Blue",
    "styleNumber": "40109",
    "season": "Fall",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "139.0",
    "shippingPrice": "10.63",
    "discount": "",
    "pricePaid": "22.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Some pilling",
    "createdAt": "2025-01-01T00:50:00.000Z"
  },
  {
    "id": "seed-1052",
    "sku": "1052",
    "image": "",
    "imageUrl": "",
    "name": "R1 Pullover",
    "category": "Fleece & Knits",
    "color": "Black",
    "styleNumber": "40109",
    "season": "Fall",
    "year": "2018",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "139.0",
    "shippingPrice": "11.78",
    "discount": "",
    "pricePaid": "11.84",
    "condition": "Good",
    "source": "eBay",
    "notes": "Embroidered logo. Removed. Put minor hole in but patched it.",
    "createdAt": "2025-01-01T00:51:00.000Z"
  },
  {
    "id": "seed-1053",
    "sku": "1053",
    "image": "",
    "imageUrl": "",
    "name": "R1 Pullover",
    "category": "Fleece & Knits",
    "color": "CHB Blue",
    "styleNumber": "40108",
    "season": "Spring",
    "year": "2015",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "129.0",
    "shippingPrice": "5.93",
    "discount": "",
    "pricePaid": "40.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:52:00.000Z"
  },
  {
    "id": "seed-1054",
    "sku": "1054",
    "image": "",
    "imageUrl": "",
    "name": "R1 TechFace Jacket",
    "category": "Fleece & Knits",
    "color": "Orange",
    "styleNumber": "83580",
    "season": "Fall",
    "year": "2020",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "189.0",
    "shippingPrice": "7.27",
    "discount": "",
    "pricePaid": "22.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Fairly worn but no major issues aside from some pilling",
    "createdAt": "2025-01-01T00:53:00.000Z"
  },
  {
    "id": "seed-1055",
    "sku": "1055",
    "image": "",
    "imageUrl": "",
    "name": "R1 Thermal Bottoms",
    "category": "Fleece & Knits",
    "color": "SMDB",
    "styleNumber": "40620",
    "season": "Fall",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "149.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "88.99",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:54:00.000Z"
  },
  {
    "id": "seed-1056",
    "sku": "1056",
    "image": "",
    "imageUrl": "",
    "name": "R1 Thermal Full-Zip Hoody",
    "category": "Fleece & Knits",
    "color": "BLK",
    "styleNumber": "40600",
    "season": "Fall",
    "year": "2024",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "219.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "91.98",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:55:00.000Z"
  },
  {
    "id": "seed-1057",
    "sku": "1057",
    "image": "",
    "imageUrl": "",
    "name": "Responsibili-Tee",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "38951",
    "season": "Fall",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "4.55",
    "discount": "",
    "pricePaid": "10.55",
    "condition": "Good",
    "source": "eBay",
    "notes": "Good condition - bit worn but no issues.",
    "createdAt": "2025-01-01T00:56:00.000Z"
  },
  {
    "id": "seed-1058",
    "sku": "1058",
    "image": "",
    "imageUrl": "",
    "name": "Stretch Wavefarer Walk Shorts 20\"",
    "category": "Shorts",
    "color": "Grey",
    "styleNumber": "86641",
    "season": "Spring",
    "year": "2017",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "69.0",
    "shippingPrice": "3.84",
    "discount": "",
    "pricePaid": "8.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:57:00.000Z"
  },
  {
    "id": "seed-1059",
    "sku": "1059",
    "image": "",
    "imageUrl": "",
    "name": "Stretch Wavefarer Volley Shorts 16\"",
    "category": "Shorts",
    "color": "Patterned",
    "styleNumber": "86511",
    "season": "Spring",
    "year": "2019",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "69.0",
    "shippingPrice": "2.85",
    "discount": "",
    "pricePaid": "8.5",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:58:00.000Z"
  },
  {
    "id": "seed-1060",
    "sku": "1060",
    "image": "",
    "imageUrl": "",
    "name": "Sunshade Technical Hoody",
    "category": "Sun Shirts & Sun Hoodies",
    "color": "Patterned",
    "styleNumber": "52657",
    "season": "Spring",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "6.0",
    "discount": "",
    "pricePaid": "20.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:59:00.000Z"
  },
  {
    "id": "seed-1061",
    "sku": "1061",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "PLGY = plume grey",
    "styleNumber": "24540",
    "season": "Spring",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "4.99",
    "discount": "",
    "pricePaid": "20.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:00:00.000Z"
  },
  {
    "id": "seed-1062",
    "sku": "1062",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "Red",
    "styleNumber": "24540",
    "season": "Fall",
    "year": "2022",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "4.99",
    "discount": "",
    "pricePaid": "20.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:01:00.000Z"
  },
  {
    "id": "seed-1063",
    "sku": "1063",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "SMDB - Smolder Blue",
    "styleNumber": "24540",
    "season": "Spring",
    "year": "2021",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "5.95",
    "discount": "",
    "pricePaid": "18.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:02:00.000Z"
  },
  {
    "id": "seed-1064",
    "sku": "1064",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "FGE - Forge Grey",
    "styleNumber": "24540",
    "season": "Fall",
    "year": "2021",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "7.0",
    "discount": "",
    "pricePaid": "21.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:03:00.000Z"
  },
  {
    "id": "seed-1065",
    "sku": "1065",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "SMDB - Smolder Blue",
    "styleNumber": "24540",
    "season": "Spring",
    "year": "2020",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "8.95",
    "discount": "",
    "pricePaid": "20.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:04:00.000Z"
  },
  {
    "id": "seed-1066",
    "sku": "1066",
    "image": "",
    "imageUrl": "",
    "name": "Torrentshell Jacket (2.5L)",
    "category": "Rain/Shells/Jackets",
    "color": "NBRR",
    "styleNumber": "83802",
    "season": "Fall",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "179.0",
    "shippingPrice": "6.09",
    "discount": "",
    "pricePaid": "49.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:05:00.000Z"
  },
  {
    "id": "seed-1067",
    "sku": "1067",
    "image": "",
    "imageUrl": "",
    "name": "Torrentshell 3L Rain Pants",
    "category": "Rain/Shells/Jackets",
    "color": "Black",
    "styleNumber": "85266",
    "season": "Spring",
    "year": "2024",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "129.0",
    "shippingPrice": "7.71",
    "discount": "",
    "pricePaid": "22.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Warranty exchanged for new",
    "createdAt": "2025-01-01T00:06:00.000Z"
  },
  {
    "id": "seed-1068",
    "sku": "1068",
    "image": "",
    "imageUrl": "",
    "name": "Transit Traveler 5-Pocket Pants",
    "category": "Pants",
    "color": "SMDB - Smolder Blue",
    "styleNumber": "22085",
    "season": "Spring",
    "year": "2024",
    "size": "Other",
    "sizeOther": "34",
    "listPrice": "139.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "58.38",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:07:00.000Z"
  },
  {
    "id": "seed-1069",
    "sku": "1069",
    "image": "",
    "imageUrl": "",
    "name": "Tropic Comfort II Hoody",
    "category": "Sun Shirts & Sun Hoodies",
    "color": "Green",
    "styleNumber": "52116",
    "season": "Spring",
    "year": "2014",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "49.0",
    "shippingPrice": "4.43",
    "discount": "",
    "pricePaid": "10.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:08:00.000Z"
  },
  {
    "id": "seed-1070",
    "sku": "1070",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Trail (with pocket)",
    "category": "Short-Sleeve Tees",
    "color": "Green",
    "styleNumber": "No tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "4.55",
    "discount": "",
    "pricePaid": "10.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "No tags, tiny hole near neck hanger",
    "createdAt": "2025-01-01T00:09:00.000Z"
  },
  {
    "id": "seed-1071",
    "sku": "1071",
    "image": "",
    "imageUrl": "",
    "name": "Venga Rock Pants",
    "category": "Pants",
    "color": "Dark Grey",
    "styleNumber": "No tag",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "34",
    "listPrice": "109.0",
    "shippingPrice": "2.85",
    "discount": "",
    "pricePaid": "15.0",
    "condition": "Good",
    "source": "Goodwill",
    "notes": "",
    "createdAt": "2025-01-01T00:10:00.000Z"
  },
  {
    "id": "seed-1072",
    "sku": "1072",
    "image": "",
    "imageUrl": "",
    "name": "R2 Jacket",
    "category": "Fleece & Knits",
    "color": "Forge Grey",
    "styleNumber": "25137",
    "season": "Fall",
    "year": "2013",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "169.0",
    "shippingPrice": "8.9",
    "discount": "",
    "pricePaid": "16.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Branding on sleeve, but may leave it",
    "createdAt": "2025-01-01T00:11:00.000Z"
  },
  {
    "id": "seed-1073",
    "sku": "1073",
    "image": "",
    "imageUrl": "",
    "name": "Baggies Shorts 5\"",
    "category": "Shorts",
    "color": "TGOR - Tigerlily Orange",
    "styleNumber": "No tag",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "69.0",
    "shippingPrice": "6.99",
    "discount": "",
    "pricePaid": "9.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:12:00.000Z"
  },
  {
    "id": "seed-1074",
    "sku": "1074",
    "image": "",
    "imageUrl": "",
    "name": "Long-Sleeved Buckshot Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "",
    "styleNumber": "53856",
    "season": "Fall",
    "year": "2015",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "7.35",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition, no signs of wear",
    "createdAt": "2025-01-01T00:13:00.000Z"
  },
  {
    "id": "seed-1075",
    "sku": "1075",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Lightweight",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "45651",
    "season": "Fall",
    "year": "2016",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "49.0",
    "shippingPrice": "4.84",
    "discount": "",
    "pricePaid": "8.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Some damage - pulls and threads, minor",
    "createdAt": "2025-01-01T00:14:00.000Z"
  },
  {
    "id": "seed-1076",
    "sku": "1076",
    "image": "",
    "imageUrl": "",
    "name": "Go-To Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "",
    "styleNumber": "52691",
    "season": "Spring",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "6.4",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Had an organic stain on the chest, came out",
    "createdAt": "2025-01-01T00:15:00.000Z"
  },
  {
    "id": "seed-1077",
    "sku": "1077",
    "image": "",
    "imageUrl": "",
    "name": "Cloud Ridge Pants",
    "category": "Rain/Shells/Jackets",
    "color": "Black",
    "styleNumber": "83695",
    "season": "Fall",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "199.0",
    "shippingPrice": "6.95",
    "discount": "",
    "pricePaid": "16.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "Good condition, no flaws",
    "createdAt": "2025-01-01T00:16:00.000Z"
  },
  {
    "id": "seed-1078",
    "sku": "1078",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Shorts 10\"",
    "category": "Pants",
    "color": "SOBL",
    "styleNumber": "24690",
    "season": "Spring",
    "year": "2021",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "5.99",
    "discount": "",
    "pricePaid": "13.46",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:17:00.000Z"
  },
  {
    "id": "seed-1079",
    "sku": "1079",
    "image": "",
    "imageUrl": "",
    "name": "Windsweep 3-in-1 Jacket",
    "category": "Rain/Shells/Jackets",
    "color": "Black",
    "styleNumber": "28090",
    "season": "Fall",
    "year": "2016",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "400.0",
    "shippingPrice": "10.0",
    "discount": "",
    "pricePaid": "34.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:18:00.000Z"
  },
  {
    "id": "seed-1080",
    "sku": "1080",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "Green",
    "styleNumber": "24540",
    "season": "Fall",
    "year": "2022",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "6.99",
    "discount": "",
    "pricePaid": "22.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:19:00.000Z"
  },
  {
    "id": "seed-1081",
    "sku": "1081",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily",
    "category": "Short-Sleeve Tees",
    "color": "Grey",
    "styleNumber": "45215",
    "season": "Spring",
    "year": "2019",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "5.99",
    "discount": "",
    "pricePaid": "8.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:20:00.000Z"
  },
  {
    "id": "seed-1082",
    "sku": "1082",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Jacket",
    "category": "Fleece & Knits",
    "color": "Black",
    "styleNumber": "25528",
    "season": "Fall",
    "year": "2019",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "8.75",
    "discount": "",
    "pricePaid": "13.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:21:00.000Z"
  },
  {
    "id": "seed-1083",
    "sku": "1083",
    "image": "",
    "imageUrl": "",
    "name": "R1 Pullover",
    "category": "Fleece & Knits",
    "color": "",
    "styleNumber": "",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "139.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "18.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:22:00.000Z"
  },
  {
    "id": "seed-1084",
    "sku": "1084",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Midweight Zip-Neck",
    "category": "Thermal Baselayers",
    "color": "",
    "styleNumber": "",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "4.84",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:23:00.000Z"
  },
  {
    "id": "seed-1085",
    "sku": "1085",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Trail",
    "category": "Short-Sleeve Tees",
    "color": "",
    "styleNumber": "",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "5.64",
    "discount": "",
    "pricePaid": "4.36",
    "condition": "Good",
    "source": "eBay",
    "notes": "Had massive stain but washed out",
    "createdAt": "2025-01-01T00:24:00.000Z"
  },
  {
    "id": "seed-1086",
    "sku": "1086",
    "image": "",
    "imageUrl": "",
    "name": "Go-To Shirt",
    "category": "Short-Sleeve Tees",
    "color": "Blue",
    "styleNumber": "52691",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "32.99",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:25:00.000Z"
  },
  {
    "id": "seed-1087",
    "sku": "1087",
    "image": "",
    "imageUrl": "",
    "name": "Long-Sleeved Dirt Craft Bike Jersey",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "",
    "styleNumber": "23891",
    "season": "",
    "year": "",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "23.76",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:26:00.000Z"
  },
  {
    "id": "seed-1088",
    "sku": "1088",
    "image": "",
    "imageUrl": "",
    "name": "Hydropeak Boardshorts 21\"",
    "category": "Shorts",
    "color": "TIDB",
    "styleNumber": "86480",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "35",
    "listPrice": "75.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "20.99",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:27:00.000Z"
  },
  {
    "id": "seed-1089",
    "sku": "1089",
    "image": "",
    "imageUrl": "",
    "name": "Hydropeak Hybrid Walk Shorts 19\"",
    "category": "Shorts",
    "color": "ENLB",
    "styleNumber": "86475",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "34",
    "listPrice": "89.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "29.39",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:28:00.000Z"
  },
  {
    "id": "seed-1090",
    "sku": "1090",
    "image": "",
    "imageUrl": "",
    "name": "Women's Capilene Cool Daily Hoody",
    "category": "Sun Shirts & Sun Hoodies",
    "color": "PMCX",
    "styleNumber": "45315",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "XXL",
    "listPrice": "65.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "22.39",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:29:00.000Z"
  },
  {
    "id": "seed-1091",
    "sku": "1091",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Daily Graphic Shirt",
    "category": "Short-Sleeve Tees",
    "color": "SBYX",
    "styleNumber": "45355",
    "season": "",
    "year": "",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "55.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "16.79",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:30:00.000Z"
  },
  {
    "id": "seed-1092",
    "sku": "1092",
    "image": "",
    "imageUrl": "",
    "name": "Lightweight '73 Text Logo Hoody",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "NENA",
    "styleNumber": "39695",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "85.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "41.29",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:31:00.000Z"
  },
  {
    "id": "seed-1093",
    "sku": "1093",
    "image": "",
    "imageUrl": "",
    "name": "Ultralight Black Hole Mini Hip Pack 1L",
    "category": "Accessories",
    "color": "PWGN",
    "styleNumber": "49447",
    "season": "",
    "year": "",
    "size": "Other",
    "sizeOther": "All",
    "listPrice": "35.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "16.79",
    "condition": "New with tags",
    "source": "Patagonia Outlet",
    "notes": "",
    "createdAt": "2025-01-01T00:32:00.000Z"
  },
  {
    "id": "seed-1094",
    "sku": "1094",
    "image": "",
    "imageUrl": "",
    "name": "Terrebonne Joggers",
    "category": "Pants",
    "color": "Black",
    "styleNumber": "24540",
    "season": "Fall",
    "year": "2021",
    "size": "Medium",
    "sizeOther": "",
    "listPrice": "99.0",
    "shippingPrice": "5.0",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "minor hole in knee",
    "createdAt": "2025-01-01T00:33:00.000Z"
  },
  {
    "id": "seed-1095",
    "sku": "1095",
    "image": "",
    "imageUrl": "",
    "name": "Capilene Cool Lightweight",
    "category": "Short-Sleeve Tees",
    "color": "Grey",
    "styleNumber": "45760",
    "season": "",
    "year": "",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "45.0",
    "shippingPrice": "4.88",
    "discount": "",
    "pricePaid": "7.98",
    "condition": "Good",
    "source": "eBay",
    "notes": "Great condition",
    "createdAt": "2025-01-01T00:34:00.000Z"
  },
  {
    "id": "seed-1096",
    "sku": "1096",
    "image": "",
    "imageUrl": "",
    "name": "Men's Long-Sleeve Pima Cotton Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "SKNB",
    "styleNumber": "53837",
    "season": "Fall",
    "year": "2018",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "5.24",
    "discount": "",
    "pricePaid": "10.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:35:00.000Z"
  },
  {
    "id": "seed-1097",
    "sku": "1097",
    "image": "",
    "imageUrl": "",
    "name": "Tropic Comfort Natural Crew Sun Shirt",
    "category": "Sun Shirts & Sun Hoodies",
    "color": "TMBL",
    "styleNumber": "41965",
    "season": "Spring",
    "year": "2025",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "89.0",
    "shippingPrice": "10.45",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:36:00.000Z"
  },
  {
    "id": "seed-1098",
    "sku": "1098",
    "image": "",
    "imageUrl": "",
    "name": "Men's Long-Sleeve Pima Cotton Shirt",
    "category": "Long-Sleeve Shirts & Wovens",
    "color": "MFG",
    "styleNumber": "53837",
    "season": "Fall",
    "year": "2011",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "8.0",
    "discount": "",
    "pricePaid": "6.5",
    "condition": "Good",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:37:00.000Z"
  },
  {
    "id": "seed-10100",
    "sku": "10100",
    "image": "",
    "imageUrl": "",
    "name": "Better Sweater Jacket",
    "category": "Fleece & Knits",
    "color": "Blue",
    "styleNumber": "25528",
    "season": "Fall",
    "year": "2019",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "159.0",
    "shippingPrice": "7.0",
    "discount": "",
    "pricePaid": "9.0",
    "condition": "Good",
    "source": "eBay",
    "notes": "Embroidered",
    "createdAt": "2025-01-01T00:38:00.000Z"
  },
  {
    "id": "seed-10101",
    "sku": "10101",
    "image": "",
    "imageUrl": "",
    "name": "Tropic Comfort II",
    "category": "Sun Shirts & Sun Hoodies",
    "color": "IBUX",
    "styleNumber": "52124",
    "season": "Spring",
    "year": "2021",
    "size": "Other",
    "sizeOther": "XL",
    "listPrice": "59.0",
    "shippingPrice": "7.0",
    "discount": "",
    "pricePaid": "12.0",
    "condition": "",
    "source": "",
    "notes": "",
    "createdAt": "2025-01-01T00:39:00.000Z"
  },
  {
    "id": "seed-10102",
    "sku": "10102",
    "image": "",
    "imageUrl": "",
    "name": "Go-To Shirt",
    "category": "Short-Sleeve Tees",
    "color": "PRGN",
    "styleNumber": "52691",
    "season": "Spring",
    "year": "2025",
    "size": "Large",
    "sizeOther": "",
    "listPrice": "79.0",
    "shippingPrice": "0.0",
    "discount": "",
    "pricePaid": "13.0",
    "condition": "New without tags",
    "source": "eBay",
    "notes": "",
    "createdAt": "2025-01-01T00:40:00.000Z"
  }
];
